# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_volume_groups <- function(x, volume) {
    .Call(`_FancyBar_find_volume_groups`, x, volume)
}

